export { AboutMe } from './about-me'
export { Contacts } from './contacts'
export { Footer } from './footer'
export { Main } from './main'
export { Portfolio } from './portfolio'
export { Skills } from './skills'
